name: Makefile CI

on:
  push:
    branches: [ "trunk" ]
  pull_request:
    branches: [ "trunk" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  linux-build:
    runs-on: ubuntu-latest
    env:
      target: release
    steps:
    - uses: actions/checkout@v3

    - name: Update apt
      run: sudo apt update

    - name: Get processor arch
      run: echo "PROCESSOR_ARCH=`uname -p`" >> $GITHUB_ENV

    - name: Install dependencies
      run: | 
        sudo apt install -y libudev-dev curl
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | bash -s -- -y
        . "$HOME/.cargo/env"
        cargo --version

    - name: Build
      run: |
        . "$HOME/.cargo/env"
        make all

    - name: Prepare Release
      working-directory: ${{github.workspace}}/tools/shift_tool/target/${{ env.target }}
      shell: bash
      run: tar --exclude='.fingerprint' --exclude='build' --exclude='deps' --exclude='examples' --exclude='incremental' --exclude='*.d' --exclude='.cargo-lock' -zcvf ${{github.workspace}}/${{ runner.os }}-${{ env.PROCESSOR_ARCH }}-shift_tool.tar.gz *

    - name: Upload linux build
      uses: actions/upload-artifact@v2
      with:
        name: linux_${{ env.target }}_build
        path: ${{github.workspace}}/${{ runner.os }}-${{ env.PROCESSOR_ARCH }}-shift_tool.tar.gz
        
  windows-build:
    runs-on: windows-latest
    env:
      target: release
    steps:
    - uses: actions/checkout@v3

    - name: Update apt
      run: sudo apt update

    - name: Build
      uses: rust-build/rust-build.action@v1.4.5
      with:
        RUSTTARGET: shift_tool
        SRC_DIR: ${{github.workspace}}/tools/shift_tool

    
