name: Makefile CI

on:
  push:
    branches: [ "trunk" ]
  pull_request:
    branches: [ "trunk" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  release:
    name: Release - ${{ matrix.platform.release_for }}
    strategy:
      matrix:
        platform:
          - release_for: Linux-x86_64
            os: ubuntu-20.04
            target: x86_64-unknown-linux-gnu
            bin: shift_tool
            name: shift_tool-Linux-x86_64.tar.gz
            command: build
            dependencies_command: sudo apt install -y libudev-dev curl

          - release_for: Windows-x86_64
            os: windows-latest
            target: x86_64-pc-windows-msvc
            bin: shift_tool.exe
            name: shift_tool-Windows-x86_64.zip
            command: build
            dependencies_command: true

    runs-on: ${{ matrix.platform.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: ${{ matrix.platform.dependencies_command }}
      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v0
        with:
          working-directory: ${{github.workspace}}/tools/shift_tool
          command: ${{ matrix.platform.command }}
          target: ${{ matrix.platform.target }}
          args: "--locked --release"
          strip: true
      - name: Prepare Release
        working-directory: ${{github.workspace}}/tools/shift_tool/target/${{ matrix.platform.target }}/release
        shell: bash
        run: tar --exclude='.fingerprint' --exclude='build' --exclude='deps' --exclude='examples' --exclude='incremental' --exclude='*.d' --exclude='.cargo-lock' -zcvf ${{github.workspace}}/${{ matrix.platform.release_for }}-shift_tool.tar.gz *
      - name: Upload build
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.platform.release_for }}_build
          path: ${{github.workspace}}/${{ matrix.platform.release_for }}-shift_tool.tar.gz

      # more packaging stuff goes here ...
#  build:
#    runs-on: ubuntu-latest
#    env:
#      target: release
#    steps:
#    - uses: actions/checkout@v3
#
#    - name: Update apt
#      run: sudo apt update
#
#    - name: Get processor arch
#      run: echo "PROCESSOR_ARCH=`uname -p`" >> $GITHUB_ENV
#
#    - name: Install dependencies
#      run: |
#        sudo apt install -y libudev-dev curl
#        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | bash -s -- -y
#        . "$HOME/.cargo/env"
#        cargo --version
#
#    - name: Build
#      run: |
#        . "$HOME/.cargo/env"
#        make all
#
#    - name: Prepare Release
#      working-directory: ${{github.workspace}}/tools/shift_tool/target/${{ env.target }}
#      shell: bash
#      run: tar --exclude='.fingerprint' --exclude='build' --exclude='deps' --exclude='examples' --exclude='incremental' --exclude='*.d' --exclude='.cargo-lock' -zcvf ${{github.workspace}}/${{ runner.os }}-${{ env.PROCESSOR_ARCH }}-shift_tool.tar.gz *
#
#    - name: Upload linux build
#      uses: actions/upload-artifact@v2
#      with:
#        name: linux_${{ env.target }}_build
#        path: ${{github.workspace}}/${{ runner.os }}-${{ env.PROCESSOR_ARCH }}-shift_tool.tar.gz
