name: Makefile CI

on:
  push:
    branches: [ "trunk" ]
  pull_request:
    branches: [ "trunk" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Update apt
      run: sudo apt update

    - name: Install dependencies
      run: | 
        sudo apt install -y libudev-dev curl
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | bash -s -- -y
        . "$HOME/.cargo/env"
        cargo --version

    - name: Build
      run: |
        . "$HOME/.cargo/env"
        make

    - name: Upload
      run:
        echo "Uploading artifacts"
